### ISSUE TITLE
Calculate CIDR block

### ISSUE THREAD

**Issue by agallo** [arineng/nicinfo#14]
Providing CIDR notation for the queried prefix would be helpful.  If I query for a host address, nicinfo will display the start and end address, but not the CIDR block that contains the info.  whois provides this info.  For example:

```
whois 2620:0:861:ed1a::1
<output truncated>
NetRange:       2620:0:860:: - 2620:0:863:FFFF:FFFF:FFFF:FFFF:FFFF
CIDR:           2620:0:860::/46
```

Having the CIDR block calculated would be helpful.

Thank you

**Comment by anewton1998** [comment]
Good suggestion. I'll look to incorporate this.

**Comment by anewton1998** [comment]
This now in 1.2 release
