### ISSUE TITLE
Switching to use bootstrap files

### ISSUE THREAD

**Issue by jtalir** [arineng/nicinfo#17]
Is there a way how to convince client to use boostrap files from IANA and not going through rdap.arin.net? IMHO this should be default.

    $ /tmp/nicinfo/bin/nicinfo -V --iana nic.cz
    # NicInfo v.1.1.0-alpha
    ## Using configuration found in /home/jara/.NicInfo
    ## Evicted 0 files from the cache
    ## Downloading http://data.iana.org/rdap/asn.json to /home/jara/.NicInfo/bsfiles
    ## Downloading http://data.iana.org/rdap/ipv4.json to /home/jara/.NicInfo/bsfile
    ## Downloading http://data.iana.org/rdap/ipv6.json to /home/jara/.NicInfo/bsfile
    ## Downloading http://data.iana.org/rdap/dns.json to /home/jara/.NicInfo/bsfiles
    ## Assuming query value is DOMAIN
    ## Issuing GET for https://rdap.arin.net/registry/domain/nic.cz
    # Query yielded no results.
    ## Server conforms to rdap_level_0
    
    [ NOTICE ] Terms of Service
             1 By using the ARIN RDAP/Whois service, you are agreeing to the
               RDAP/Whois Terms of Use
         About https://www.arin.net/whois_tou.html
    
     [ ERROR ] DOMAIN NOT FOUND
          Code 404
             1 The domain you are seeking as 'nic.cz.' is/are not here.
    
    ## Server response code was 404'

**Comment by anewton1998** [comment]
It should be using the IANA files by default. Let me look into this.

**Comment by anewton1998** [comment]
This is fixed in 1.1.1 (just released).

Here's what the issue was. The IANA files were being consulted, but the parsing of the file was failing. And that was failing because the bootstrapping code for NicInfo was written before the RDAP IANA bootstrapping RFC was published, and between the two events the JSON was changed in a subtle yet incompatible way.

**Comment by jtalir** [comment]
Thanks!
