### ISSUE TITLE
URI encode updated in Ruby 3.1.2

### ISSUE THREAD

**Issue by anthonycarrette** [arineng/nicinfo#42]
~/.rvm/gems/ruby-3.1.2/gems/nicinfo-1.5.0/lib/nicinfo/nicinfo_main.rb:322:in `get': undefined method `encode' for URI:Module (NoMethodError)

19a20
\> require 'addressable/uri'

322,323c323,324
<         uri = URI.parse( URI::encode( url ) )
<         req = Net::HTTP::Get.new(uri.request_uri)
\---
 \>        uri = URI.parse( Addressable::URI.escape( url ) )
 \>         req = Net::HTTP::Get.new(uri)'

379,380c380,381
<       uri = URI.parse( URI::encode( url ) )
<       req = Net::HTTP::Get.new(uri.request_uri)
\---
\>       uri = URI.parse( Addressable::URI.escape( url ) )
\>       req = Net::HTTP::Get.new(uri)

**Comment by gdubin** [comment]
Thank you for reporting this.  It's been fixed and a new version has been pushed to rubygems.org.
