### ISSUE TITLE
Ruby 3.2.0 File class exist(s) method name change

### ISSUE THREAD

**Issue by va4500** [arineng/nicinfo#43]
# NicInfo v.1.5.1
/opt/homebrew/lib/ruby/gems/3.2.0/gems/nicinfo-1.5.1/lib/nicinfo/config.rb:134:in `get_bsfiles_last_update_time': undefined method>

      if File.exists?( fname )
             ^^^^^^^^
Did you mean?  exist?
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/nicinfo-1.5.1/lib/nicinfo/config.rb:150:in `check_bsfiles_age?'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/nicinfo-1.5.1/lib/nicinfo/nicinfo_main.rb:425:in `run'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/nicinfo-1.5.1/bin/nicinfo:25:in `<top (required)>'

https://stackoverflow.com/questions/14351272/why-do-i-get-undefined-method-exist-for-fileclass

**Comment by marek22k** [comment]
I get the same error :-(

**Comment by gdubin** [comment]
This has been fixed in 1.5.2.  Thanks for reporting this.
